spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-Id: 47258385080-9g1pksnq3l1a81seanf9aollnb2oh4cn.apps.googleusercontent.com
            client-secret: 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
